name: 部署项目到 Github Pages

on:
  push:
    branches: [master]

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: yarn install
      - name: Build with VitePress
        run: yarn docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  # 部署工作
  deploy_github:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  deploy_server:
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.SERVER_HOST }} # 在仓库设置中添加服务器 IP 作为 secrets
      username: ${{ secrets.SERVER_USERNAME }} # 添加服务器用户名作为 secrets
      password: ${{ secrets.SERVER_PASSWORD }} # 添加服务器密码作为 secrets（或者使用密钥认证）
      script: |
        rm -rf /var/www/html/stundejzw.github.io/*
        cp -R docs/.vitepress/dist /var/www/html/stundejzw.github.io/
